---
- name: Deploy {{ target }} 
  hosts: "{{ target }}"
  vars:
    openshift_login_url: "https://console.s9.core.rht-labs.com"
    openshift:
      common:
        client_binary: "/usr/bin/oc"
        admin_binary: "/usr/bin/oc adm"
    ci_cd:
      namespace: ci-cd
    dev:
      namespace: dev
    test:
      namespace: test
    prod:
      namespace: prod
  tasks:
    - include_tasks: tasks/oc-setup.yml
      tags:
        - setup
        - login
    - include_role:
        name: casl-ansible/roles/openshift-login
      tags:
        - login
    - include_role:
        name: openshift-applier/roles/openshift-applier