---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: admin
  roleRef:
    name: admin
  userNames:
#  - system:serviceaccount:management-infra:management-admin
  - pcarney